[bumpver]
current_version = "3.37.1"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"CMN_binViewer.py" = ['version = "{version}"',]
"CMN_binViewer_setup.iss"= ['AppVersion="{version}"$',]
"CMN_binViewer_setup_win32.iss"= ['AppVersion="{version}"$',]
